### ISSUE TITLE
Feature request - MQTT  / Tasmota/ SOnoff

### ISSUE THREAD

**Issue by SoundGuy** [devildant/OctoPrint-ShutdownPrinter#1]
Is there a way to collaborate with the Tasmota plugin to send a request to shut down the printer power via MQTT for Tasmota Sonoff firmware?

https://github.com/jneilliii/OctoPrint-Tasmota

**Comment by devildant** [comment]
hello, "shutdown printer" send a GCODE M81 with IP.
I see that in the Sonoff-Tasmota settings there is a Gcode trigger option.
there may be a track on that side

**Comment by SoundGuy** [comment]
I have some bug in my printer that can't allow anything as parameter after M80 / M81. is it possible to send those GCODE without the IP as parameter?

**Comment by devildant** [comment]
just remove IP (TPLINK IP) in settings and save

**Comment by MrPasty** [comment]
I agree with this, if you could integrate Sonoff this would be amazing

**Comment by devildant** [comment]
I designed this plugin to act as a remote control.
Once the triggering events have been detected, the plugin sends the M81 code followed by the contents of the TPLINK IP field.
So, in theory, any other plugin that reads events will be able to perform an action with this gcode.
I do not intend to integrate the management of the connected plugs (they are much too varied)

**Comment by jneilliii** [comment]
I agree about the way too many variations.  I'm pushing a release now that resolved @SoundGuy's issue with Repetier and strips away everything after the M80/M81 commands.

@MrPasty: I'm not sure if you've seen my Tasmota plugins (there are two) that work with sonoff devices.

**Comment by MrPasty** [comment]
I have seen the Tasmota plugin but i like the feature on this one to send a shutdown command if the nozzle reaches a certain temperature, or am i missing the fact yours does this as well?

**Comment by devildant** [comment]
Warning,
this setting (nozzle temperature) is only there to allow the fan to cool the nozzle before stopping the printer after **printing**.

**Comment by MrPasty** [comment]
Perfect, thanks for taking the time to help me.

**Comment by SoundGuy** [comment]
as can be seen in @jneilliii 's repository this is working for me - 

https://github.com/jneilliii/OctoPrint-TasmotaMQTT/issues/11

I set the TPLINK name to be the Tasmota name (in my case SonoffPrinter) then this plugin sens M81 SonOffPrinter that is being caught after the temprature dropped below 100degc and then it sends an empty M81 to the printer and it works like a charm! 
I can finaly leave home knowing the printer won't run while i'm away. i'm very happy about it

**Comment by devildant** [comment]
perfect :) 
I change the label" TPLINK IP" by "Parameter (IP or other)" (for next release)

**Comment by sepodele** [comment]
Does that mean it would work with Domoticz to turn off a switch if I use this instead of TPLINK IP?

http://ip:port/json.htm?type=command&param=switchlight&idx=99&switchcmd=Off

**Comment by devildant** [comment]
Hello, this plugin works with tplink, after a complete print, "shutdown printer", request the stop plug to tplink (or other similar plugin)

**Comment by sepodele** [comment]
Right. I was just hoping it was possible for the plugin to run a web request like the URL i posted. That would make it possible to turn off my power plugs through Domoticz (home automation application). If not possible, that's another feature request. ;)

**Comment by devildant** [comment]
each plugin has an API: https://github.com/devildant/OctoPrint-ShutdownPrinter/blob/master/octoprint_shutdownprinter/__init__.py#LC100
currently the "shutdown printer" API allows to switch on / off the shutdown option of the printer

**Comment by sepodele** [comment]
Not sure I follow. I was hoping I could use your plugin to switch off my power plug that my printer is connected to.

**Comment by devildant** [comment]
why do not you use the TPLINK plugin for that ?

**Comment by sepodele** [comment]
I dont' have a TPLINK power plug. The power plugs I have run on Z-Wave protocol (not WiFi), controlled via a web server called Domoticz. To control the power plugs I can run a http json command like this: http://192.168.0.10:8080/json.htm?type=command&param=switchlight&idx=99&switchcmd=Off

So I was hoping your plugin could run that command when print was complete.

**Comment by devildant** [comment]
ah OK, I recently added a mode (API) in the plugin, but it is limited to octoprint, when I will have time I could perhaps try to open it at the other URL (different from 127.0.0.1)

**Comment by sepodele** [comment]
Thanks. Fingers crossed. :)

**Comment by jneilliii** [comment]
It wouldn't be too difficult for me to fork my tasmota web based plugin to do this. Can you tell me what the response is when you go to that url you posted?

**Comment by sepodele** [comment]
{
"status": "OK",
"title": "SwitchLight"
}

More info here: https://www.domoticz.com/wiki/Domoticz_API/JSON_URL's#Turn_a_light.2Fswitch_off

**Comment by jneilliii** [comment]
Can you tell me what you get when you run the following command with your switches IDX?

http://192.168.0.10:8080/json.htm?type=devices&rid=IDX

**Comment by sepodele** [comment]
https://pastebin.com/cds4fKSi

**Comment by jneilliii** [comment]
Thanks, just to confirm, if you turn it off and run the same command the Status on line 50 becomes "Off"? I'm pretty close to having this ready for you for testing.

**Comment by sepodele** [comment]
Yes. Both Status and Data becomes 'Off'. I think it's best to use Status.

**Comment by jneilliii** [comment]
Perfect.  Install using the url below in plugin manager.  Once loaded we should be able to test using the buttons in the navbar first.  It should detect the current status of either On and Off and turn the icon the appropriate color based on status.  When you add your switch use the pattern ip:port and the index will be the index you use for your switch in the Domoticz server. Please report issues in the issue tracker on the repository [here](https://github.com/jneilliii/OctoPrint-Domoticz/issues). Specifically would need to check the logs for any errors, etc.

https://github.com/jneilliii/OctoPrint-Domoticz/archive/master.zip

**Comment by jneilliii** [comment]
You may want to hold off a bit.  I just tried to install and don't think it's working correctly.  I'll let you know when it's at least installing so you can test.

**Comment by jneilliii** [comment]
Ok, I got it installing and seems to be sending the correct web requests in order to work for you.  Give it a try and let me know. This is what I meant about ip:port configuration. I didn't install Domoticz because not sure if it's compatible with my devices I have, but this should work in theory.

![image](https://user-images.githubusercontent.com/5249455/42398684-d00c96d4-8138-11e8-9f9a-53797ac1f643.png)

**Comment by jneilliii** [comment]
@devildant this will not work with domoticz server switches using [OctoPrint-Domoticz](https://github.com/jneilliii/OctoPrint-Domoticz) in theory by using a pattern of `<server ip>:<server port> <switch index>` @sepodele would have to confirm that part, but it is working for him to control his plug through domoticz now, and I am assuming it will integrate with your as well since it uses the same M81 commands to control via GCODE.

**Comment by sepodele** [comment]
It works. 👍

**Comment by devildant** [comment]
hello @jneilliii , @sepodele ,
i developed a new mode on "shutdown printer" (custom API mode), now it is possible to call a WS (POST / GET) with custom header / body

**Comment by devildant** [comment]
@jneilliii you were faster than me :)
a dedicated plugin to domoticz is better :)

**Comment by sepodele** [comment]
@devildant I saw that but I don't understand how to use it. What goes where?

**Comment by devildant** [comment]
mode GCODE : send gcode M81 IP
mode API : call an octoprint plugin via its name, with a json body (parameter of the plugin api)
mode API custom : call a external URL (with GET or not parameters)
example: http: //IP: PORT/path?p1=1&p2=2
you can put the header if necessary
example : 
{"Content-type" : "application/json"}
you can put the  body if necessary
{ "toto" : "titi" }
and you can choose if send in POST or GET (GET only URL and header use, POST use URL, header and body)
