### ISSUE TITLE
[Documentation] Events Catch configuration feature

### ISSUE THREAD

**Issue by talldonkey** [devildant/OctoPrint-ShutdownPrinter#12]
What does the Events Catch configuration do?   It's not clear to me what it actually does?

**Comment by devildant** [comment]
there is 3 events that stops a print :
- print done
- print cancel
- print failed
by default the plugin activates only on the Print done
as a result the "catch event" section allows to trigger the plugin if a print is cancel or failed.

activated the event "print failed" can be an extra security if the printer ever encounters an error.
