### ISSUE TITLE
Installation of ShutdownPrinter 1.0.5 kills interactive fields in other plugins

### ISSUE THREAD

**Issue by devosthomas** [devildant/OctoPrint-ShutdownPrinter#15]
I installed first the Tasmota plugin from Jneillliii, and it worked like it should. Then I installed ShutdownPrinter 1.0.5 but that broke the Tasmota plugin. The Tasmota screen is now empty. not able to create a new plug and even the buttons don't work. Not only the Tasmota plugin is affected but my other plugins too like Bed Visualizer etc... I restarted Octopi several times to test all scenario's. The interfaces seems all to be broken. If I disable the ShutdownPrinter plugin they all work like they should.

**Tasmota before installation of the plugin** 
<img width="615" alt="Tasmota Before ShutdownPrinter installation" src="https://user-images.githubusercontent.com/10219005/62832770-25340c00-bc34-11e9-8daf-27d8f731532e.png">

**Tasmota after installation of the plugin**
<img width="618" alt="Tasmota After ShutdownPrinter installation" src="https://user-images.githubusercontent.com/10219005/62832799-91167480-bc34-11e9-93c0-8852d14ee2ca.png">

Any help would be great!

**Comment by devildant** [comment]
Hello,

sorry, it was a JS error, which was caused by a pull request, I did not have time to test it.
the error is corrected
please update shutdown printer with version 1.0.7

**Comment by devosthomas** [comment]
That fixed it! Thanks for the swift reply and fix!
