### ISSUE TITLE
Issue a shell command to do the turning off

### ISSUE THREAD

**Issue by kevinkahn** [devildant/OctoPrint-ShutdownPrinter#7]
Is there any easy way to just issue a shell command to actually turn off the printer?  I have defined a pair of system commands in OctoPrint that use "sudo gpio ..." to control printer power since the power is directly handled by the pi via a control pin.  I'd like to be able to just issue the appropriate command from the plug-in when it decides to turn off the printer.

**Comment by devildant** [comment]
hello, for the moment I have not implemented this solution, I add it to my list of tasks. I will implement it as soon as possible.

**Comment by devildant** [comment]
hello, I found 5 minutes to make a quick fix, I added the possibility in the preferences of the plugin, to add a gcode custom (mode gcode).
with the plugin: actioncommands (https://plugins.octoprint.org/plugins/actioncommands/)
you should be able to do what you want
