### ISSUE TITLE
FEATURE REQUEST

### ISSUE THREAD

**Issue by bloodygoodbloke** [devildant/OctoPrint-ShutdownPrinter#8]
the ability to shutdown PI at the same time

**Comment by devildant** [comment]
a raspberry is not intended to be extinguished.
the shutdown command turns off part of the pi, but this one remains powered.

there is a plugin for that : https://plugins.octoprint.org/plugins/automaticshutdown/
but I do not see the interest.
best regards

**Comment by bloodygoodbloke** [comment]
i have my PI wired into the PSU of the printer.  if i turn off via the TPlink plug then it kills Octopi unceremoniously.  I dont know if there is a way to embed a delay into the TPlink shutdown to allow PI to execute the TPlink but shutdown its-self cleanly

**Comment by devildant** [comment]
without delay actually this is impossible.
see directly with the creator of the tplink plugin : https://plugins.octoprint.org/plugins/tplinksmartplug/

**Comment by philipptrenz** [comment]
Hey, thanks for your great work! I want to do just that!

I'm using a DeConz Zigbee Gateway with smart sockets. The API of the gateway provides to define delayed schedules (see [here](http://dresden-elektronik.github.io/deconz-rest-doc/schedules/)). As the display of my printer is lighted as long as it's connected to the Pi I want to shutdown also the power supply to the Pi.

So it would be great if the Plugin provides:
- An option to also shutdown the Pi after a print job ended
- An *events catch* for "Event will-shutdown of the Pi" to trigger the API when clicking on shutdown within the UI navigation bar

Thanks a lot!

**Comment by devildant** [comment]
Hello,
at the limit I could add an option "extra command", which allows to run a script at the same time as the plug off.
Be careful though, the pi must not be connected to the plug that will be turned off.
also after the shudown the PI remains powered (led on)

**Comment by philipptrenz** [comment]
Hi @devildant, thanks for the quick reply.

Perfect! As my plug shuts down delayed (e.g. one minute after API call) the Pi has enough time to securely shutting down, so this is just fine for me.

Is it possible to catch a "shutdown" event of Octopi  or the click on the shutdown button to also trigger a API call in this case?

**Comment by devildant** [comment]
@philipptrenz, If I add the ability to call a script, you can do whatever you want, call your API and execute the shutdown command.
but you will have to code your script on your side.
I want to stay as generic as possible

**Comment by devildant** [comment]
ha i just understand you want me to intercept the octoprint shutdown command?

**Comment by philipptrenz** [comment]
> ha i just understand you want me to intercept the octoprint shutdown command?

Additionally to the custom shell command, yeah 😄

**Comment by devildant** [comment]
nothing prevents you from putting a script here
![image](https://user-images.githubusercontent.com/8700106/57582906-f1c5d200-74ca-11e9-9689-01e5e27da6ba.png)

**Comment by philipptrenz** [comment]
Ah, thanks for this hint! So I'll add my curl command there. Thanks!

**Comment by devildant** [comment]
I made a quick implementation of the extra command
could you try this : 
https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/dev.zip

**Comment by philipptrenz** [comment]
Works like a charm, many thanks!

**Comment by philipptrenz** [comment]
I switched back to the stable branch, but I think you forgot to raise the `plugin_version` in `setup.py` to 1.0.4. Nevertheless from my standpoint this issue can be closed ;)

**Comment by devildant** [comment]
oops, I forgot to push :p
it's fix, https://github.com/devildant/OctoPrint-ShutdownPrinter/archive/1.0.4.zip
