### ISSUE TITLE
Feature Request regarding Timelapse

### ISSUE THREAD

**Issue by KenshiHH** [devildant/OctoPrint-ShutdownPrinter#9]
hey,
awesome plugin.

right now i shut the pinter down when my hotend reaches 40°C, would it also be possible to also delay the shutdown until the timelapse rendering is complete?

on bigger prints the rendering of the timelapse takes longer than the nozzle to cool down so the rendered timelapse is missing most of the footage.

**Comment by devildant** [comment]
hello, 
normally the pi should be able to finish processing on the timelapse even if the printer is turned off.
 unless your pi is connected to your outlet like the printer, if it's the case it's not a good idea

**Comment by KenshiHH** [comment]
yeah i should have mentioned it that i also shutdown my pi with octoprint on it, my bad :)

**Comment by devildant** [comment]
Hello, this is a behavior that I want to avoid.
I understand the desire to extinguish the pi at the end of an impression.
But currently there is no way to turn off the PI properly, without the support of a delay on the connected plug, one can not turn off the printer with the PI.
You are currently doing it in a violent way via the plug, except that, the PI is a server, doing this you risk corrupting the data.
I can not favor this type of behavior.
I'am sorry

**Comment by KenshiHH** [comment]
I use your plugin to send a shutdown command to the pi and the pi sends a timer command to the tasmota flashed plug, there is never a violent shutdown of the pi, the pi shuts down, 2 minutes later the plug switches to off.

yeah no problem if its not a feature you want, still a great plugin :)

**Comment by KenshiHH** [comment]
yes, a sonoff plug flashed with tasmota supports rules and timers.

the only thing is missing right for my setup is the status of the timelapse to trigger the shutdown.

guess i have to set a 30min delay to make sure the timelapse rendering gets done on bigger prints before the shutdown

**Comment by devildant** [comment]
Ok, in this case, I will look at this feature as soon as I have time and if I find an octoprint event indicating the status of the timelapse.
for now I'm creating another plugin: p

**Comment by KenshiHH** [comment]
i have found a fix for my problem, the timelapse gets renderes with "avconv", i added a while loop into my script the check every 5 seconds if avconv is still running :)
